@startuml project
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity user {
  *id: int
  *username: string
  *hash_password: string
}

entity job-application{
  *id: int
  *title: string
}

entity job-source{
  *id: int
  *title: int
}

entity company {
  *id: int
}

@enduml
